const mongoose=require("mongoose")
const laonpendingschema=new mongoose.Schema({
    customer:{
        type:String
    },
    loannumber:{
        type:Number
    },
    dueamount:{
        type:Number
    },
    paidamount:{
        type:Number
    },
    totalamount:{
        type:Number
    },
    startdate:{
        type:Date
    },
    givendate:{
        type:Date
    },
    receipdate:{
        type:Date
    },
    collectedamount:{
        type:Number
    },
    _id:mongoose.Schema.Types.ObjectId,
    customer_id:{
        type:mongoose.Schema.Types.ObjectId,
        default:""
    },
    lineman_id:{
        type:mongoose.Schema.Types.ObjectId,
        default:""
    },
    weekno:{
        type:Number
    },
    bookno:{
        type:Number
    },
    document:{
        type:String
    },
    cheque:{
        type:String
    },
    weekcount:{
        type:Number
    },
    duedate:{
        type:Date
    },
    finisheddate:{
        type:Date
    },
    givenamount:{
        type:Number
    },
    documentamount:{
        type:Number
    },
    interestamount:{
        type:Number
    },
     customer:{
        type:String,
        default:""
    },
    city:{
        type:mongoose.Schema.Types.ObjectId,
        default:""
    },
    cityid:{
        type:String,
        default:""
    },
    fathername:{
        type:String,
        default:""
    },
    work:{
        type:String,
        default:""
    },
    address:{
        type:String,
        default:""
    },
    mobileno:{
        type:String,
        default:""
    },
    lineno:{
        type:String,
        default:""
    }

},{collection:'vw_ledger',versionKey:false});
module.exports=mongoose.model('Ledger',laonpendingschema);
